/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.Controller;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel
 */
public class NewBBDD extends javax.swing.JDialog {

    Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons2/database.png"));
    
    /**
     * Creates new form NewBBDD
     */
    public NewBBDD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("New BBDD");
        setIconImage(icon);
        //Select
        conectionEnabledSelectData.setEditable(false);
        conectionEnabledSelectData.setBackground(Color.LIGHT_GRAY);
        conectionEnabledSelectData.setText("");
        
        //Delete
        conectionFieldDelete.setEditable(false);
        conectionFieldDelete.setBackground(Color.LIGHT_GRAY);
        conectionFieldDelete.setText("");
        
        //Update
        conectionUpdateData.setEditable(false);
        conectionUpdateData.setBackground(Color.LIGHT_GRAY);
        conectionUpdateData.setText("");
        
        //Query
        conectionDataQuery.setEditable(false);
        conectionDataQuery.setBackground(Color.LIGHT_GRAY);
        conectionDataQuery.setText("");
        
        //Insert
        connectionDataInsert.setEditable(false);
        connectionDataInsert.setBackground(Color.LIGHT_GRAY);
        connectionDataInsert.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tabsSelect = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();
        deleteRowSelectResult = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSelectResult = new javax.swing.JTable();
        addSelectResult = new javax.swing.JButton();
        resultSelectField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tableLabel = new javax.swing.JLabel();
        tableFieldSelect = new javax.swing.JTextField();
        deleteRowSelectTable = new javax.swing.JButton();
        addSelectTable = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSelectTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        conditionSelectCondicion = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        conditionSelectConditionText = new javax.swing.JTextArea();
        conectionSelect = new javax.swing.JLabel();
        userSelect = new javax.swing.JLabel();
        userSelectData = new javax.swing.JTextField();
        passSelect = new javax.swing.JLabel();
        passSelectData = new javax.swing.JTextField();
        conectionCheckSelect = new javax.swing.JLabel();
        conectionBoolean = new javax.swing.JCheckBox();
        conectionEnabledSelectData = new javax.swing.JTextField();
        aceptSelect = new javax.swing.JButton();
        cancelSelect = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        tabsDelete = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        tablaLAbelDelete = new javax.swing.JLabel();
        tableTextDelete = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        conectionLabelDelete = new javax.swing.JLabel();
        userLabelDelete = new javax.swing.JLabel();
        userDeleteData = new javax.swing.JTextField();
        passLabelDelete = new javax.swing.JLabel();
        passDeleteData = new javax.swing.JTextField();
        conectionLabelEnabledDelete = new javax.swing.JLabel();
        enabledConnectionDelete = new javax.swing.JCheckBox();
        conectionFieldDelete = new javax.swing.JTextField();
        acceptButtonDelete = new javax.swing.JButton();
        cancelButtonDelete = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        tabsUpdate = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tableUpdateData = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableUpdateTable = new javax.swing.JTable();
        deleteRowUpdateTable = new javax.swing.JButton();
        addUpdateTable = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fieldsDataUpdate = new javax.swing.JTextField();
        deleteRowUpdateFields = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableFieldsUpdateFields = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        conditionTextAreaUpdateCondition = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userUpdateData = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passUpdateData = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        enabledConectionUpdate = new javax.swing.JCheckBox();
        conectionUpdateData = new javax.swing.JTextField();
        acceptButtonUpdate = new javax.swing.JButton();
        cancelButtonUpdate = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        queryTextArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        userDataQuery = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        passDataQuery = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        enableConectionquery = new javax.swing.JCheckBox();
        conectionDataQuery = new javax.swing.JTextField();
        acceptQuery = new javax.swing.JButton();
        cancelQuery = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        tabsInsert = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        fieldsDataInsert = new javax.swing.JTextField();
        deleteRowInsertFields = new javax.swing.JButton();
        addInsertFields = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        fieldsInsertTable = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        tableDataInsert = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        columnDataInsert = new javax.swing.JTextField();
        clearTableInsertColumns = new javax.swing.JButton();
        deleteRowInsertColumns = new javax.swing.JButton();
        addInsertColumns = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tableColumnsInsert = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        userDataInsert = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        passDataInsert = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        enabledConnectionInsert = new javax.swing.JCheckBox();
        connectionDataInsert = new javax.swing.JTextField();
        acceptButtonInsert = new javax.swing.JButton();
        cancelButtonInsert = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        resultLabel.setText("Result:");

        deleteRowSelectResult.setText("Delete Row");
        deleteRowSelectResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowSelectResultActionPerformed(evt);
            }
        });

        tablaSelectResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resultado"
            }
        ));
        jScrollPane1.setViewportView(tablaSelectResult);

        addSelectResult.setText("Add to Table");
        addSelectResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSelectResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteRowSelectResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSelectResult))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(resultLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultSelectField))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultLabel)
                    .addComponent(resultSelectField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteRowSelectResult)
                    .addComponent(addSelectResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsSelect.addTab("Result", jPanel2);

        tableLabel.setText("Table:");

        deleteRowSelectTable.setText("Delete row");
        deleteRowSelectTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowSelectTableActionPerformed(evt);
            }
        });

        addSelectTable.setText("Add to table");
        addSelectTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSelectTableActionPerformed(evt);
            }
        });

        tablaSelectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table"
            }
        ));
        jScrollPane2.setViewportView(tablaSelectTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteRowSelectTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSelectTable))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tableLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableFieldSelect)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableLabel)
                    .addComponent(tableFieldSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteRowSelectTable)
                    .addComponent(addSelectTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsSelect.addTab("Table", jPanel3);

        conditionSelectCondicion.setText("Condition:");

        conditionSelectConditionText.setColumns(20);
        conditionSelectConditionText.setRows(5);
        jScrollPane3.setViewportView(conditionSelectConditionText);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(conditionSelectCondicion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(conditionSelectCondicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsSelect.addTab("Condition", jPanel4);

        conectionSelect.setText("Connection");

        userSelect.setText("User:");

        passSelect.setText("Pass:");

        conectionCheckSelect.setText("Connection:");

        conectionBoolean.setText("Enabled");
        conectionBoolean.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                conectionBooleanStateChanged(evt);
            }
        });
        conectionBoolean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectionBooleanActionPerformed(evt);
            }
        });

        conectionEnabledSelectData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectionEnabledSelectDataActionPerformed(evt);
            }
        });

        aceptSelect.setText("Accept");
        aceptSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptSelectActionPerformed(evt);
            }
        });

        cancelSelect.setText("Cancel");
        cancelSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aceptSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(cancelSelect))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(conectionCheckSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(conectionBoolean))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passSelectData))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(conectionSelect)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(userSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userSelectData))
                    .addComponent(conectionEnabledSelectData))
                .addGap(18, 18, 18)
                .addComponent(tabsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(conectionSelect)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userSelect)
                            .addComponent(userSelectData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passSelect)
                            .addComponent(passSelectData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conectionCheckSelect)
                            .addComponent(conectionBoolean))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(conectionEnabledSelectData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aceptSelect)
                            .addComponent(cancelSelect)))
                    .addComponent(tabsSelect))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Select", jPanel1);

        tablaLAbelDelete.setText("Table:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableTextDelete)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(tablaLAbelDelete)
                        .addGap(0, 339, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(tablaLAbelDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableTextDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        tabsDelete.addTab("Table", jPanel6);

        jLabel2.setText("Condition:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsDelete.addTab("Condition", jPanel7);

        conectionLabelDelete.setText("Connection");

        userLabelDelete.setText("User:");

        passLabelDelete.setText("Pass:");

        conectionLabelEnabledDelete.setText("Connection:");

        enabledConnectionDelete.setText("Enabled");
        enabledConnectionDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enabledConnectionDeleteActionPerformed(evt);
            }
        });

        conectionFieldDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectionFieldDeleteActionPerformed(evt);
            }
        });

        acceptButtonDelete.setText("Accept");

        cancelButtonDelete.setText("Cancel");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(acceptButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(cancelButtonDelete))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(conectionLabelEnabledDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(enabledConnectionDelete))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(passLabelDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passDeleteData))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(conectionLabelDelete)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(userLabelDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userDeleteData))
                    .addComponent(conectionFieldDelete))
                .addGap(18, 18, 18)
                .addComponent(tabsDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(conectionLabelDelete)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userLabelDelete)
                            .addComponent(userDeleteData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passLabelDelete)
                            .addComponent(passDeleteData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conectionLabelEnabledDelete)
                            .addComponent(enabledConnectionDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(conectionFieldDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acceptButtonDelete)
                            .addComponent(cancelButtonDelete)))
                    .addComponent(tabsDelete))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Delete", jPanel5);

        jLabel7.setText("Table:");

        tableUpdateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table"
            }
        ));
        jScrollPane5.setViewportView(tableUpdateTable);

        deleteRowUpdateTable.setText("Delete Row");
        deleteRowUpdateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowUpdateTableActionPerformed(evt);
            }
        });

        addUpdateTable.setText("Add to Table");
        addUpdateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUpdateTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteRowUpdateTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addUpdateTable))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tableUpdateData)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tableUpdateData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteRowUpdateTable)
                    .addComponent(addUpdateTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsUpdate.addTab("Table", jPanel9);

        jLabel8.setText("Fields:");

        deleteRowUpdateFields.setText("Delete Row");
        deleteRowUpdateFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowUpdateFieldsActionPerformed(evt);
            }
        });

        jButton1.setText("Add to Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableFieldsUpdateFields.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fields"
            }
        ));
        jScrollPane6.setViewportView(tableFieldsUpdateFields);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldsDataUpdate))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(deleteRowUpdateFields)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldsDataUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteRowUpdateFields)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsUpdate.addTab("Fields", jPanel10);

        jLabel9.setText("Condition:");

        conditionTextAreaUpdateCondition.setColumns(20);
        conditionTextAreaUpdateCondition.setRows(5);
        jScrollPane7.setViewportView(conditionTextAreaUpdateCondition);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsUpdate.addTab("Condition", jPanel11);

        jLabel3.setText("Connection");

        jLabel4.setText("User:");

        jLabel5.setText("Pass:");

        jLabel6.setText("Connection:");

        enabledConectionUpdate.setText("Enabled");
        enabledConectionUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enabledConectionUpdateActionPerformed(evt);
            }
        });

        acceptButtonUpdate.setText("Accept");
        acceptButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonUpdateActionPerformed(evt);
            }
        });

        cancelButtonUpdate.setText("Cancel");
        cancelButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(acceptButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(cancelButtonUpdate))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(enabledConectionUpdate))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passUpdateData))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userUpdateData))
                    .addComponent(conectionUpdateData))
                .addGap(18, 18, 18)
                .addComponent(tabsUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(userUpdateData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(passUpdateData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(enabledConectionUpdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(conectionUpdateData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acceptButtonUpdate)
                            .addComponent(cancelButtonUpdate)))
                    .addComponent(tabsUpdate))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Update", jPanel8);

        jLabel14.setText("Query Sentence:");

        queryTextArea.setColumns(20);
        queryTextArea.setRows(5);
        jScrollPane8.setViewportView(queryTextArea);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Sentence", jPanel13);

        jLabel10.setText("Connection");

        jLabel11.setText("User:");

        jLabel12.setText("Pass:");

        jLabel13.setText("Connection:");

        enableConectionquery.setText("Enabled");
        enableConectionquery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableConectionqueryActionPerformed(evt);
            }
        });

        conectionDataQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectionDataQueryActionPerformed(evt);
            }
        });

        acceptQuery.setText("Accept");

        cancelQuery.setText("Cancel");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(acceptQuery)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(cancelQuery))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enableConectionquery))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passDataQuery))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userDataQuery))
                    .addComponent(conectionDataQuery))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(userDataQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(passDataQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(enableConectionquery))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(conectionDataQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acceptQuery)
                            .addComponent(cancelQuery)))
                    .addComponent(jTabbedPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Query", jPanel12);

        jLabel19.setText("Fields:");

        deleteRowInsertFields.setText("Delete Row");

        addInsertFields.setText("Add to Table");

        fieldsInsertTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fields"
            }
        ));
        jScrollPane9.setViewportView(fieldsInsertTable);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteRowInsertFields)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addInsertFields))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldsDataInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(fieldsDataInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteRowInsertFields)
                    .addComponent(addInsertFields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsInsert.addTab("Fields", jPanel15);

        jLabel20.setText("Table:");

        tableDataInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableDataInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 339, Short.MAX_VALUE))
                    .addComponent(tableDataInsert))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableDataInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        tabsInsert.addTab("Table", jPanel16);

        jLabel21.setText("Column:");

        clearTableInsertColumns.setText("Clear Table");

        deleteRowInsertColumns.setText("Delete Row");
        deleteRowInsertColumns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowInsertColumnsActionPerformed(evt);
            }
        });

        addInsertColumns.setText("Add to Table");

        tableColumnsInsert.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Columns"
            }
        ));
        jScrollPane10.setViewportView(tableColumnsInsert);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(columnDataInsert))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel17Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clearTableInsertColumns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteRowInsertColumns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addInsertColumns)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(columnDataInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearTableInsertColumns)
                    .addComponent(deleteRowInsertColumns)
                    .addComponent(addInsertColumns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsInsert.addTab("Columns", jPanel17);

        jLabel15.setText("Connection");

        jLabel16.setText("User:");

        jLabel17.setText("Pass:");

        jLabel18.setText("Connection:");

        enabledConnectionInsert.setText("Enabled");
        enabledConnectionInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enabledConnectionInsertActionPerformed(evt);
            }
        });

        connectionDataInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionDataInsertActionPerformed(evt);
            }
        });

        acceptButtonInsert.setText("Accept");

        cancelButtonInsert.setText("Cancel");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(acceptButtonInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(cancelButtonInsert))
                    .addComponent(connectionDataInsert)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enabledConnectionInsert))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passDataInsert))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userDataInsert)))
                .addGap(18, 18, 18)
                .addComponent(tabsInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(userDataInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(passDataInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enabledConnectionInsert)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(connectionDataInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acceptButtonInsert)
                            .addComponent(cancelButtonInsert)))
                    .addComponent(tabsInsert))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Insert", jPanel14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteRowSelectTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowSelectTableActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaSelectTable.getModel();
        if (tablaSelectTable.getSelectedRow() != -1)
            model.removeRow(tablaSelectTable.getSelectedRow());
    }//GEN-LAST:event_deleteRowSelectTableActionPerformed

    private void tableDataInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableDataInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDataInsertActionPerformed

    private void deleteRowInsertColumnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowInsertColumnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteRowInsertColumnsActionPerformed

    private void addSelectResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSelectResultActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) tablaSelectResult.getModel();
        String type = "";
        String result = resultSelectField.getText();
        resultSelectField.setText("");
        model.addRow(new Object[]{result});
    }//GEN-LAST:event_addSelectResultActionPerformed

    private void addSelectTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSelectTableActionPerformed
       
        DefaultTableModel model = (DefaultTableModel) tablaSelectTable.getModel();
        String type = "";
        String table = tableFieldSelect.getText();
        tableFieldSelect.setText("");
        model.addRow(new Object[]{table});
    }//GEN-LAST:event_addSelectTableActionPerformed

    private void aceptSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptSelectActionPerformed

        boolean error = false;
        String errorString = "";
        Object[] what = new Object[7];
        what[0] = conectionBoolean.isSelected();
        what[1] = userSelectData.getText();
        what[2] = passSelectData.getText();
        what[3] = conectionEnabledSelectData.getText();
        ArrayList resultadoSelect = new ArrayList();
        ArrayList tablaSelect = new ArrayList();
        int filas = tablaSelectResult.getRowCount();
        for (int i = 0; i < filas; i++) {
            resultadoSelect.add((String)tablaSelectResult.getValueAt(i, 0));
        }
        if (filas == 0) {
            error = true;
            errorString += "Result field is not filled.\n";
        }
        what[4] = resultadoSelect;
        filas = tablaSelectTable.getRowCount();
        for (int i = 0; i < filas; i++) {
            tablaSelect.add((String)tablaSelectTable.getValueAt(i, 0));
        }
        if (filas == 0) {
            error = true;
            errorString += "Table field is not filled.\n";
        }
        what[5] = tablaSelect;
        what[6] = conditionSelectConditionText.getText();
        if (conditionSelectConditionText.getText().equalsIgnoreCase("")) {
            error = true;
            errorString += "Condition field is not filled.\n";
        }
        if (!error) {
        Controller.controller(Controller.SELECTBD, what);
        this.dispose();
        } else {
            JOptionPane op = new JOptionPane();
            int messagetype = JOptionPane.ERROR_MESSAGE; //JOptionPane.INFORMATION_MESSAGE
            op.showMessageDialog(this, errorString, "[ERROR] Some fields are not filled", messagetype);
        }
    }//GEN-LAST:event_aceptSelectActionPerformed

    private void deleteRowSelectResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowSelectResultActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaSelectResult.getModel();
        if (tablaSelectResult.getSelectedRow() != -1)
            model.removeRow(tablaSelectResult.getSelectedRow());
    }//GEN-LAST:event_deleteRowSelectResultActionPerformed

    private void cancelSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSelectActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelSelectActionPerformed

    private void acceptButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonUpdateActionPerformed
        boolean error = false;
        String errorString = "";
        Object[] what = new Object[7];
        what[0] = enabledConectionUpdate.isSelected();
        what[1] = userUpdateData.getText();
        what[2] = passUpdateData.getText();
        what[3] = conectionUpdateData.getText();
        ArrayList tablaUpdate = new ArrayList();
        ArrayList fieldsUpdate = new ArrayList();
        int filas = tableUpdateTable.getRowCount();
        for (int i = 0; i < filas; i++) {
            tablaUpdate.add((String)tableUpdateTable.getValueAt(i, 0));
        }
        if (filas == 0) {
            error = true;
            errorString += "Table field is not filled.\n";
        }
        what[4] = tablaUpdate;
        filas = tableFieldsUpdateFields.getRowCount();
        for (int i = 0; i < filas; i++) {
            fieldsUpdate.add((String)tableFieldsUpdateFields.getValueAt(i, 0));
        }
        if (filas == 0) {
            error = true;
            errorString += "Field field is not filled.\n";
        }
        what[5] = fieldsUpdate;
        what[6] = conditionTextAreaUpdateCondition.getText();
        if (conditionTextAreaUpdateCondition.getText().equalsIgnoreCase("")) {
            error = true;
            errorString += "Condition field is not filled.\n";
        }
        if (!error) {
        Controller.controller(Controller.UPDATEBD, what);
        this.dispose();
        } else {
            JOptionPane op = new JOptionPane();
            int messagetype = JOptionPane.ERROR_MESSAGE; //JOptionPane.INFORMATION_MESSAGE
            op.showMessageDialog(this, errorString, "[ERROR] Some fields are not filled", messagetype);
        }
    }//GEN-LAST:event_acceptButtonUpdateActionPerformed

    private void deleteRowUpdateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowUpdateTableActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableUpdateTable.getModel();
        if (tableUpdateTable.getSelectedRow() != -1)
            model.removeRow(tableUpdateTable.getSelectedRow());
    }//GEN-LAST:event_deleteRowUpdateTableActionPerformed

    private void deleteRowUpdateFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowUpdateFieldsActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableFieldsUpdateFields.getModel();
        if (tableFieldsUpdateFields.getSelectedRow() != -1)
            model.removeRow(tableFieldsUpdateFields.getSelectedRow());
    }//GEN-LAST:event_deleteRowUpdateFieldsActionPerformed

    private void addUpdateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUpdateTableActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableUpdateTable.getModel();
        String type = "";
        String table = tableUpdateData.getText();
        tableUpdateData.setText("");
        model.addRow(new Object[]{table});
    }//GEN-LAST:event_addUpdateTableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableFieldsUpdateFields.getModel();
        String type = "";
        String table = fieldsDataUpdate.getText();
        fieldsDataUpdate.setText("");
        model.addRow(new Object[]{table});
    }//GEN-LAST:event_jButton1ActionPerformed

    private void conectionBooleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectionBooleanActionPerformed
        if (conectionEnabledSelectData.isEditable()) {
            conectionEnabledSelectData.setEditable(false);
            conectionEnabledSelectData.setBackground(Color.LIGHT_GRAY);
            conectionEnabledSelectData.setText("");
        } else {
            conectionEnabledSelectData.setEditable(true);
            conectionEnabledSelectData.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_conectionBooleanActionPerformed

    private void conectionBooleanStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_conectionBooleanStateChanged
      
    }//GEN-LAST:event_conectionBooleanStateChanged

    private void cancelButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonUpdateActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonUpdateActionPerformed

    private void enabledConectionUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enabledConectionUpdateActionPerformed
        if (conectionUpdateData.isEditable()) {
            conectionUpdateData.setEditable(false);
            conectionUpdateData.setBackground(Color.LIGHT_GRAY);
            conectionUpdateData.setText("");
        } else {
            conectionUpdateData.setEditable(true);
            conectionUpdateData.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_enabledConectionUpdateActionPerformed

    private void conectionFieldDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectionFieldDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conectionFieldDeleteActionPerformed

    private void conectionDataQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectionDataQueryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conectionDataQueryActionPerformed

    private void connectionDataInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionDataInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectionDataInsertActionPerformed

    private void conectionEnabledSelectDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectionEnabledSelectDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conectionEnabledSelectDataActionPerformed

    private void enabledConnectionDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enabledConnectionDeleteActionPerformed
        if (conectionFieldDelete.isEditable()) {
            conectionFieldDelete.setEditable(false);
            conectionFieldDelete.setBackground(Color.LIGHT_GRAY);
            conectionFieldDelete.setText("");
        } else {
            conectionFieldDelete.setEditable(true);
            conectionFieldDelete.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_enabledConnectionDeleteActionPerformed

    private void enableConectionqueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableConectionqueryActionPerformed
        if (conectionDataQuery.isEditable()) {
            conectionDataQuery.setEditable(false);
            conectionDataQuery.setBackground(Color.LIGHT_GRAY);
            conectionDataQuery.setText("");
        } else {
            conectionDataQuery.setEditable(true);
            conectionDataQuery.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_enableConectionqueryActionPerformed

    private void enabledConnectionInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enabledConnectionInsertActionPerformed
        if (connectionDataInsert.isEditable()) {
            connectionDataInsert.setEditable(false);
            connectionDataInsert.setBackground(Color.LIGHT_GRAY);
            connectionDataInsert.setText("");
        } else {
            connectionDataInsert.setEditable(true);
            connectionDataInsert.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_enabledConnectionInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButtonDelete;
    private javax.swing.JButton acceptButtonInsert;
    private javax.swing.JButton acceptButtonUpdate;
    private javax.swing.JButton acceptQuery;
    private javax.swing.JButton aceptSelect;
    private javax.swing.JButton addInsertColumns;
    private javax.swing.JButton addInsertFields;
    private javax.swing.JButton addSelectResult;
    private javax.swing.JButton addSelectTable;
    private javax.swing.JButton addUpdateTable;
    private javax.swing.JButton cancelButtonDelete;
    private javax.swing.JButton cancelButtonInsert;
    private javax.swing.JButton cancelButtonUpdate;
    private javax.swing.JButton cancelQuery;
    private javax.swing.JButton cancelSelect;
    private javax.swing.JButton clearTableInsertColumns;
    private javax.swing.JTextField columnDataInsert;
    private javax.swing.JLabel conditionSelectCondicion;
    private javax.swing.JTextArea conditionSelectConditionText;
    private javax.swing.JTextArea conditionTextAreaUpdateCondition;
    private javax.swing.JCheckBox conectionBoolean;
    private javax.swing.JLabel conectionCheckSelect;
    private javax.swing.JTextField conectionDataQuery;
    private javax.swing.JTextField conectionEnabledSelectData;
    private javax.swing.JTextField conectionFieldDelete;
    private javax.swing.JLabel conectionLabelDelete;
    private javax.swing.JLabel conectionLabelEnabledDelete;
    private javax.swing.JLabel conectionSelect;
    private javax.swing.JTextField conectionUpdateData;
    private javax.swing.JTextField connectionDataInsert;
    private javax.swing.JButton deleteRowInsertColumns;
    private javax.swing.JButton deleteRowInsertFields;
    private javax.swing.JButton deleteRowSelectResult;
    private javax.swing.JButton deleteRowSelectTable;
    private javax.swing.JButton deleteRowUpdateFields;
    private javax.swing.JButton deleteRowUpdateTable;
    private javax.swing.JCheckBox enableConectionquery;
    private javax.swing.JCheckBox enabledConectionUpdate;
    private javax.swing.JCheckBox enabledConnectionDelete;
    private javax.swing.JCheckBox enabledConnectionInsert;
    private javax.swing.JTextField fieldsDataInsert;
    private javax.swing.JTextField fieldsDataUpdate;
    private javax.swing.JTable fieldsInsertTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField passDataInsert;
    private javax.swing.JTextField passDataQuery;
    private javax.swing.JTextField passDeleteData;
    private javax.swing.JLabel passLabelDelete;
    private javax.swing.JLabel passSelect;
    private javax.swing.JTextField passSelectData;
    private javax.swing.JTextField passUpdateData;
    private javax.swing.JTextArea queryTextArea;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField resultSelectField;
    private javax.swing.JLabel tablaLAbelDelete;
    private javax.swing.JTable tablaSelectResult;
    private javax.swing.JTable tablaSelectTable;
    private javax.swing.JTable tableColumnsInsert;
    private javax.swing.JTextField tableDataInsert;
    private javax.swing.JTextField tableFieldSelect;
    private javax.swing.JTable tableFieldsUpdateFields;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JTextField tableTextDelete;
    private javax.swing.JTextField tableUpdateData;
    private javax.swing.JTable tableUpdateTable;
    private javax.swing.JTabbedPane tabsDelete;
    private javax.swing.JTabbedPane tabsInsert;
    private javax.swing.JTabbedPane tabsSelect;
    private javax.swing.JTabbedPane tabsUpdate;
    private javax.swing.JTextField userDataInsert;
    private javax.swing.JTextField userDataQuery;
    private javax.swing.JTextField userDeleteData;
    private javax.swing.JLabel userLabelDelete;
    private javax.swing.JLabel userSelect;
    private javax.swing.JTextField userSelectData;
    private javax.swing.JTextField userUpdateData;
    // End of variables declaration//GEN-END:variables
}
