/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.MainWindow.Black;
import static GUI.MainWindow.Gray;
import controller.Controller;
import deliver.Deliver;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author NasK
 */
public class NewOperations extends javax.swing.JDialog {

    /**
     * Creates new form NewOperations
     */
    public NewOperations(JFrame frame) {
        initComponents();
        MyinitComponents(frame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ErrorWindow = new javax.swing.JDialog();
        ErrorLabel = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        orderFormat = new javax.swing.JTextField();
        orderFormatInsert = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        commandFormatExe = new javax.swing.JTextField();
        commandFormatExeInsert = new javax.swing.JButton();
        commandFormatSintax = new javax.swing.JTextField();
        commandFormatSintaxInsert = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        failureManagerFormat = new javax.swing.JTextField();
        failureManagerFormatInsert = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        concatOperationSintax = new javax.swing.JTextField();
        concatOperationSintaxInsert = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        compAsigOperationSintax = new javax.swing.JTextField();
        compAsigOperationSintaxInsert = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        basicProcessingFormat = new javax.swing.JTextField();
        basicProcessingFormatInsert = new javax.swing.JButton();
        newProcessingFormat = new javax.swing.JTextField();
        newProcessingFormatInsert = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        associationFormat = new javax.swing.JTextField();
        associationFormatInsert = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        specialEventFormat = new javax.swing.JTextField();
        specialEventFormatInsert = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        ErrorWindow.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ErrorWindow.setTitle("[ERROR] Formato de entrada invalido");
        ErrorWindow.setLocationByPlatform(true);
        ErrorWindow.setMinimumSize(new java.awt.Dimension(312, 142));
        ErrorWindow.setModal(true);
        ErrorWindow.setResizable(false);

        ErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorLabel.setText("jLabel1");

        javax.swing.GroupLayout ErrorWindowLayout = new javax.swing.GroupLayout(ErrorWindow.getContentPane());
        ErrorWindow.getContentPane().setLayout(ErrorWindowLayout);
        ErrorWindowLayout.setHorizontalGroup(
            ErrorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        ErrorWindowLayout.setVerticalGroup(
            ErrorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        jSplitPane1.setDividerLocation(270);
        jSplitPane1.setEnabled(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(270, 45));

        orderFormat.setText("X_ORDEN_SINTAX");
        orderFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderFormatActionPerformed(evt);
            }
        });
        orderFormat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                orderFormatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                orderFormatFocusLost(evt);
            }
        });

        orderFormatInsert.setText("Insert");
        orderFormatInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderFormatInsertActionPerformed(evt);
            }
        });

        commandFormatExe.setText("C_EJECUTA_COMANDO");
        commandFormatExe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandFormatExeActionPerformed(evt);
            }
        });
        commandFormatExe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                commandFormatExeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                commandFormatExeFocusLost(evt);
            }
        });

        commandFormatExeInsert.setText("Insert");
        commandFormatExeInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandFormatExeInsertActionPerformed(evt);
            }
        });

        commandFormatSintax.setText("C_SINTAXIS_COMANDO");
        commandFormatSintax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandFormatSintaxActionPerformed(evt);
            }
        });
        commandFormatSintax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                commandFormatSintaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                commandFormatSintaxFocusLost(evt);
            }
        });

        commandFormatSintaxInsert.setText("Insert");
        commandFormatSintaxInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandFormatSintaxInsertActionPerformed(evt);
            }
        });

        failureManagerFormat.setText("CAMPOS_GF");
        failureManagerFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                failureManagerFormatActionPerformed(evt);
            }
        });
        failureManagerFormat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                failureManagerFormatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                failureManagerFormatFocusLost(evt);
            }
        });

        failureManagerFormatInsert.setText("Insert");
        failureManagerFormatInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                failureManagerFormatInsertActionPerformed(evt);
            }
        });

        concatOperationSintax.setText("X_OPERACION_SINTAX");
        concatOperationSintax.setToolTipText("SUMA-CONCATENACION");
        concatOperationSintax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concatOperationSintaxActionPerformed(evt);
            }
        });
        concatOperationSintax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                concatOperationSintaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                concatOperationSintaxFocusLost(evt);
            }
        });

        concatOperationSintaxInsert.setText("Insert");
        concatOperationSintaxInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concatOperationSintaxInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(orderFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(orderFormatInsert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(commandFormatExe, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(commandFormatExeInsert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(commandFormatSintax, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(commandFormatSintaxInsert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(failureManagerFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(failureManagerFormatInsert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(concatOperationSintax, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(concatOperationSintaxInsert)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderFormatInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commandFormatExe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commandFormatExeInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commandFormatSintax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commandFormatSintaxInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(failureManagerFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(failureManagerFormatInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concatOperationSintax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concatOperationSintaxInsert))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(270, 45));

        compAsigOperationSintax.setText("X_OPERACION_SINTAX");
        compAsigOperationSintax.setToolTipText("COMPARACION-ASIGNACION");
        compAsigOperationSintax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compAsigOperationSintaxActionPerformed(evt);
            }
        });
        compAsigOperationSintax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                compAsigOperationSintaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                compAsigOperationSintaxFocusLost(evt);
            }
        });

        compAsigOperationSintaxInsert.setText("Insert");
        compAsigOperationSintaxInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compAsigOperationSintaxInsertActionPerformed(evt);
            }
        });

        basicProcessingFormat.setText("_TRATAR_BASICO");
        basicProcessingFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicProcessingFormatActionPerformed(evt);
            }
        });
        basicProcessingFormat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                basicProcessingFormatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                basicProcessingFormatFocusLost(evt);
            }
        });

        basicProcessingFormatInsert.setText("Insert");
        basicProcessingFormatInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicProcessingFormatInsertActionPerformed(evt);
            }
        });

        newProcessingFormat.setText("_TRATAR_NUEVO");
        newProcessingFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProcessingFormatActionPerformed(evt);
            }
        });
        newProcessingFormat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newProcessingFormatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newProcessingFormatFocusLost(evt);
            }
        });

        newProcessingFormatInsert.setText("Insert");
        newProcessingFormatInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProcessingFormatInsertActionPerformed(evt);
            }
        });

        associationFormat.setText("X_ASOCIAR_SINTAX");
        associationFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationFormatActionPerformed(evt);
            }
        });
        associationFormat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                associationFormatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                associationFormatFocusLost(evt);
            }
        });

        associationFormatInsert.setText("Insert");
        associationFormatInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationFormatInsertActionPerformed(evt);
            }
        });

        specialEventFormat.setText("_SPECIAL_");
        specialEventFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialEventFormatActionPerformed(evt);
            }
        });
        specialEventFormat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                specialEventFormatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                specialEventFormatFocusLost(evt);
            }
        });

        specialEventFormatInsert.setText("Insert");
        specialEventFormatInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialEventFormatInsertActionPerformed(evt);
            }
        });

        closeButton.setText("Close");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(compAsigOperationSintax, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(compAsigOperationSintaxInsert))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(basicProcessingFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(basicProcessingFormatInsert))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(newProcessingFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newProcessingFormatInsert))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(associationFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(associationFormatInsert))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(closeButton)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(specialEventFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(specialEventFormatInsert))))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compAsigOperationSintax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compAsigOperationSintaxInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basicProcessingFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basicProcessingFormatInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newProcessingFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProcessingFormatInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(associationFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(associationFormatInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specialEventFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specialEventFormatInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc=" MyinitComponents ">
    private void MyinitComponents(JFrame frame) {
        this.setTitle("New Operations");
        this.setModal(true);
        this.setLocationRelativeTo(frame);
        
        Deliver.setOrigin(this);
        Deliver.setDestination(frame);
        
        orderFormat.setForeground(Gray);
        commandFormatExe.setForeground(Gray);
        commandFormatSintax.setForeground(Gray);
        failureManagerFormat.setForeground(Gray);
        concatOperationSintax.setForeground(Gray);
        compAsigOperationSintax.setForeground(Gray);
        basicProcessingFormat.setForeground(Gray);
        newProcessingFormat.setForeground(Gray);
        associationFormat.setForeground(Gray);
        specialEventFormat.setForeground(Gray);

        orderFormat.setText("X_ORDEN_SINTAX");
        commandFormatExe.setText("C_EJECUTA_COMANDO");
        commandFormatSintax.setText("C_SINTAXIS_COMANDO");
        failureManagerFormat.setText("CAMPOS_GF");
        concatOperationSintax.setText("X_OPERACION_SINTAX");
        compAsigOperationSintax.setText("X_OPERACION_SINTAX");
        basicProcessingFormat.setText("_TRATAR_BASICO");
        newProcessingFormat.setText("_TRATAR_NUEVO");
        associationFormat.setText("X_ASOCIAR_SINTAX");
        specialEventFormat.setText("_SPECIAL_");

        orderFormatInsert.requestFocus();
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Acciones Comunes ">
    private void opActions(int Index, JTextField jtf, JButton jb, String preText) {
        if (!jtf.getText().equalsIgnoreCase(preText)) {
            //Controller.controller(Index, jtf.getText());
            if (preText.equalsIgnoreCase("")) {
                jtf.setForeground(Black);
            } else {
                jtf.setForeground(Gray);
            }
            jtf.setText(preText);
            jb.requestFocus();
        }
    }

    private void opFocus(JTextField jtf, String preText, Color c, String postText) {
        if (jtf.getText().equalsIgnoreCase(preText)) {
            jtf.setForeground(c);
            jtf.setText(postText);
        }
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" TextField & Buttons ">
    
    //<editor-fold defaultstate="collapsed" desc=" 1.orderFormat ">
    private void orderFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderFormatActionPerformed
        int Index = Controller.orderFormat;
        JTextField jtf = orderFormat;
        JButton jb = orderFormatInsert;
        String preText = "";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_orderFormatActionPerformed

    private void orderFormatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_orderFormatFocusGained
        JTextField jtf = orderFormat;
        String preText = "X_ORDEN_SINTAX";
        Color c = Black;
        String postText = "";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_orderFormatFocusGained

    private void orderFormatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_orderFormatFocusLost
        JTextField jtf = orderFormat;
        String preText = "";
        Color c = Gray;
        String postText = "X_ORDEN_SINTAX";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_orderFormatFocusLost

    private void orderFormatInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderFormatInsertActionPerformed
        int Index = Controller.orderFormat;
        JTextField jtf = orderFormat;
        JButton jb = orderFormatInsert;
        String preText = "X_ORDEN_SINTAX";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_orderFormatInsertActionPerformed
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" 2.commandFormatExe ">
    private void commandFormatExeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandFormatExeActionPerformed
        int Index = Controller.commandFormatExe;
        JTextField jtf = commandFormatExe;
        JButton jb = commandFormatExeInsert;
        String preText = "";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_commandFormatExeActionPerformed

    private void commandFormatExeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_commandFormatExeFocusGained
        JTextField jtf = commandFormatExe;
        String preText = "C_EJECUTA_COMANDO";
        Color c = Black;
        String postText = "";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_commandFormatExeFocusGained

    private void commandFormatExeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_commandFormatExeFocusLost
        JTextField jtf = commandFormatExe;
        String preText = "";
        Color c = Gray;
        String postText = "C_EJECUTA_COMANDO";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_commandFormatExeFocusLost

    private void commandFormatExeInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandFormatExeInsertActionPerformed
        int Index = Controller.commandFormatExe;
        JTextField jtf = commandFormatExe;
        JButton jb = commandFormatExeInsert;
        String preText = "C_EJECUTA_COMANDO";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_commandFormatExeInsertActionPerformed
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" 3.commandFormatSintax ">
    private void commandFormatSintaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandFormatSintaxActionPerformed
        int Index = Controller.commandFormatSintax;
        JTextField jtf = commandFormatSintax;
        JButton jb = commandFormatSintaxInsert;
        String preText = "";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_commandFormatSintaxActionPerformed

    private void commandFormatSintaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_commandFormatSintaxFocusGained
        JTextField jtf = commandFormatSintax;
        String preText = "C_SINTAXIS_COMANDO";
        Color c = Black;
        String postText = "";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_commandFormatSintaxFocusGained

    private void commandFormatSintaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_commandFormatSintaxFocusLost
        JTextField jtf = commandFormatSintax;
        String preText = "";
        Color c = Gray;
        String postText = "C_SINTAXIS_COMANDO";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_commandFormatSintaxFocusLost

    private void commandFormatSintaxInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandFormatSintaxInsertActionPerformed
        int Index = Controller.commandFormatSintax;
        JTextField jtf = commandFormatSintax;
        JButton jb = commandFormatSintaxInsert;
        String preText = "C_SINTAXIS_COMANDO";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_commandFormatSintaxInsertActionPerformed
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" 4.failureManagerFormat ">
    private void failureManagerFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_failureManagerFormatActionPerformed
        int Index = Controller.failureManagerFormat;
        JTextField jtf = failureManagerFormat;
        JButton jb = failureManagerFormatInsert;
        String preText = "";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_failureManagerFormatActionPerformed

    private void failureManagerFormatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_failureManagerFormatFocusGained
        JTextField jtf = failureManagerFormat;
        String preText = "CAMPOS_GF";
        Color c = Black;
        String postText = "";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_failureManagerFormatFocusGained

    private void failureManagerFormatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_failureManagerFormatFocusLost
        JTextField jtf = failureManagerFormat;
        String preText = "";
        Color c = Gray;
        String postText = "CAMPOS_GF";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_failureManagerFormatFocusLost

    private void failureManagerFormatInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_failureManagerFormatInsertActionPerformed
        int Index = Controller.failureManagerFormat;
        JTextField jtf = failureManagerFormat;
        JButton jb = failureManagerFormatInsert;
        String preText = "CAMPOS_GF";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_failureManagerFormatInsertActionPerformed
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" 5.concatOperationSintax ">
    private void concatOperationSintaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concatOperationSintaxActionPerformed
        int Index = Controller.concatOperationSintax;
        JTextField jtf = concatOperationSintax;
        JButton jb = concatOperationSintaxInsert;
        String preText = "";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_concatOperationSintaxActionPerformed

    private void concatOperationSintaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_concatOperationSintaxFocusGained
        JTextField jtf = concatOperationSintax;
        String preText = "X_OPERACION_SINTAX";
        Color c = Black;
        String postText = "";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_concatOperationSintaxFocusGained

    private void concatOperationSintaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_concatOperationSintaxFocusLost
        JTextField jtf = concatOperationSintax;
        String preText = "";
        Color c = Gray;
        String postText = "X_OPERACION_SINTAX";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_concatOperationSintaxFocusLost

    private void concatOperationSintaxInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concatOperationSintaxInsertActionPerformed
        int Index = Controller.concatOperationSintax;
        JTextField jtf = concatOperationSintax;
        JButton jb = concatOperationSintaxInsert;
        String preText = "X_OPERACION_SINTAX";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_concatOperationSintaxInsertActionPerformed
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" 6.compAsigOperationSintax ">
    private void compAsigOperationSintaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compAsigOperationSintaxActionPerformed
        int Index = Controller.compAsigOperationSintax;
        JTextField jtf = compAsigOperationSintax;
        JButton jb = compAsigOperationSintaxInsert;
        String preText = "";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_compAsigOperationSintaxActionPerformed

    private void compAsigOperationSintaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_compAsigOperationSintaxFocusGained
        JTextField jtf = compAsigOperationSintax;
        String preText = "X_OPERACION_SINTAX";
        Color c = Black;
        String postText = "";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_compAsigOperationSintaxFocusGained

    private void compAsigOperationSintaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_compAsigOperationSintaxFocusLost
        JTextField jtf = compAsigOperationSintax;
        String preText = "";
        Color c = Gray;
        String postText = "X_OPERACION_SINTAX";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_compAsigOperationSintaxFocusLost

    private void compAsigOperationSintaxInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compAsigOperationSintaxInsertActionPerformed
        int Index = Controller.compAsigOperationSintax;
        JTextField jtf = compAsigOperationSintax;
        JButton jb = compAsigOperationSintaxInsert;
        String preText = "X_OPERACION_SINTAX";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_compAsigOperationSintaxInsertActionPerformed
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" 7.basicProcessingFormat ">
    private void basicProcessingFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicProcessingFormatActionPerformed
        int Index = Controller.basicProcessingFormat;
        JTextField jtf = basicProcessingFormat;
        JButton jb = basicProcessingFormatInsert;
        String preText = "";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_basicProcessingFormatActionPerformed

    private void basicProcessingFormatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_basicProcessingFormatFocusGained
        JTextField jtf = basicProcessingFormat;
        String preText = "_TRATAR_BASICO";
        Color c = Black;
        String postText = "";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_basicProcessingFormatFocusGained

    private void basicProcessingFormatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_basicProcessingFormatFocusLost
        JTextField jtf = basicProcessingFormat;
        String preText = "";
        Color c = Gray;
        String postText = "_TRATAR_BASICO";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_basicProcessingFormatFocusLost

    private void basicProcessingFormatInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicProcessingFormatInsertActionPerformed
        int Index = Controller.basicProcessingFormat;
        JTextField jtf = basicProcessingFormat;
        JButton jb = basicProcessingFormatInsert;
        String preText = "_TRATAR_BASICO";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_basicProcessingFormatInsertActionPerformed
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" 8.newProcessingFormat ">
    private void newProcessingFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProcessingFormatActionPerformed
        int Index = Controller.newProcessingFormat;
        JTextField jtf = newProcessingFormat;
        JButton jb = newProcessingFormatInsert;
        String preText = "";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_newProcessingFormatActionPerformed

    private void newProcessingFormatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newProcessingFormatFocusGained
        JTextField jtf = newProcessingFormat;
        String preText = "_TRATAR_NUEVO";
        Color c = Black;
        String postText = "";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_newProcessingFormatFocusGained

    private void newProcessingFormatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newProcessingFormatFocusLost
        JTextField jtf = newProcessingFormat;
        String preText = "";
        Color c = Gray;
        String postText = "_TRATAR_NUEVO";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_newProcessingFormatFocusLost

    private void newProcessingFormatInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProcessingFormatInsertActionPerformed
        int Index = Controller.newProcessingFormat;
        JTextField jtf = newProcessingFormat;
        JButton jb = newProcessingFormatInsert;
        String preText = "_TRATAR_NUEVO";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_newProcessingFormatInsertActionPerformed
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" 9.associationFormat ">
    private void associationFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationFormatActionPerformed
        int Index = Controller.associationFormat;
        JTextField jtf = associationFormat;
        JButton jb = associationFormatInsert;
        String preText = "";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_associationFormatActionPerformed

    private void associationFormatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_associationFormatFocusGained
        JTextField jtf = associationFormat;
        String preText = "X_ASOCIAR_SINTAX";
        Color c = Black;
        String postText = "";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_associationFormatFocusGained

    private void associationFormatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_associationFormatFocusLost
        JTextField jtf = associationFormat;
        String preText = "";
        Color c = Gray;
        String postText = "X_ASOCIAR_SINTAX";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_associationFormatFocusLost

    private void associationFormatInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationFormatInsertActionPerformed
        int Index = Controller.associationFormat;
        JTextField jtf = associationFormat;
        JButton jb = associationFormatInsert;
        String preText = "X_ASOCIAR_SINTAX";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_associationFormatInsertActionPerformed
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" 10.specialEventFormat ">
    private void specialEventFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialEventFormatActionPerformed
        int Index = Controller.specialEventFormat;
        JTextField jtf = specialEventFormat;
        JButton jb = specialEventFormatInsert;
        String preText = "";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_specialEventFormatActionPerformed

    private void specialEventFormatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_specialEventFormatFocusGained
        JTextField jtf = specialEventFormat;
        String preText = "_SPECIAL_";
        Color c = Black;
        String postText = "";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_specialEventFormatFocusGained

    private void specialEventFormatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_specialEventFormatFocusLost
        JTextField jtf = specialEventFormat;
        String preText = "";
        Color c = Gray;
        String postText = "_SPECIAL_";

        opFocus(jtf, preText, c, postText);
    }//GEN-LAST:event_specialEventFormatFocusLost

    private void specialEventFormatInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialEventFormatInsertActionPerformed
        int Index = Controller.specialEventFormat;
        JTextField jtf = specialEventFormat;
        JButton jb = specialEventFormatInsert;
        String preText = "_SPECIAL_";

        opActions(Index, jtf, jb, preText);
    }//GEN-LAST:event_specialEventFormatInsertActionPerformed
    //</editor-fold>
    
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" FailureManager ">
    public void showError(String error) {
        String[] es = error.split("@");
        ErrorWindow.setLocationRelativeTo(this);
        String Text = "<html><b>Ejemplo Entrada:</b><br>"
                + "<i>" + es[0] + "</i><br><br>"
                + "<b>Ejemplo Salida:</b><br>"
                + "<i>" + es[1] + "</i></html>";
        ErrorLabel.setText(Text);
        ErrorWindow.setVisible(true);
    }
    //</editor-fold>
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JDialog ErrorWindow;
    private javax.swing.JTextField associationFormat;
    private javax.swing.JButton associationFormatInsert;
    private javax.swing.JTextField basicProcessingFormat;
    private javax.swing.JButton basicProcessingFormatInsert;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField commandFormatExe;
    private javax.swing.JButton commandFormatExeInsert;
    private javax.swing.JTextField commandFormatSintax;
    private javax.swing.JButton commandFormatSintaxInsert;
    private javax.swing.JTextField compAsigOperationSintax;
    private javax.swing.JButton compAsigOperationSintaxInsert;
    private javax.swing.JTextField concatOperationSintax;
    private javax.swing.JButton concatOperationSintaxInsert;
    private javax.swing.JTextField failureManagerFormat;
    private javax.swing.JButton failureManagerFormatInsert;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField newProcessingFormat;
    private javax.swing.JButton newProcessingFormatInsert;
    private javax.swing.JTextField orderFormat;
    private javax.swing.JButton orderFormatInsert;
    private javax.swing.JTextField specialEventFormat;
    private javax.swing.JButton specialEventFormatInsert;
    // End of variables declaration//GEN-END:variables
}
