/*
 * The main output of the program. This class manages the Syntax file that the
 * application will create.
 */
package business;
import java.io.*;
import java.util.Stack;
import java.util.Arraylist;
/**
 *
 * @author Kiwi
 */
public class Syntax {
    
	private Stack<String> syntaxStack = new Stack<String>();
	private Stack<String> auxStack = new Stack<String>();
	private boolean canBeRedone=false;
	/**
	*This method takes a string (the output) and creates a .txt file with it.
	* @param result: the string generated by the application.
	*/
	public static void publishOutput() {
	
		File f = new File("Syntax.txt");
		
		FileWriter w = new FileWriter(f);
		BufferedWriter bw = new BufferedWriter(w);
		PrintWriter wr = new PrintWriter(bw);  
		List<String> auxList = new ArrayList<String>();
		try{
		while(!auxStack.empty()){ //Clears out the stack content
			auxStack.pop();
		}
		while(!SyntaxStack.empty()){ //Prepares the lines to be written in the right order
			auxStack.push(syntaxStack.pop());
		}
		wr.write(auxStack.pop()); //It writes the first line
		
		while(!auxStack.empty()){ //This loop writes the following lines
			wr.append(auxStack.pop()); 
		}
		
		wr.close();
		bw.close();
		}catch(IOException e){};

	}
	
	public static void push(String line) {
		
		syntaxStack.push(line);
		canBeRedone=false;
	}
	
	public static void undo() {
		
		String line= syntaxStack.pop();
		if(!line.equals(null))
			auxStack.push(line);
		canBeRedone=true;
	}
	
	public static void redo() {
		if(!auxStack.empty())
			synxtaxStack.push(auxStack.pop());
	
	}

